// Mock job postings (job-seeker side). Replaced by the backend later.
import type { JobPosting } from "@/lib/types";

export const jobPostings: JobPosting[] = [
  { id: "j1", title: "Barman na wesele", profession: "Barman", district: "Mokotów", distanceKm: 3, rate: 50, hours: 8, when: "week", whenDate: "sob. 14 cze", employer: "Restauracja Vega", employerVerified: true, postedAgo: "2 godz. temu", description: "Obsługa baru na weselu ~120 gości. Wymagane doświadczenie, własny strój." },
  { id: "j2", title: "Kelner/kelnerka — event firmowy", profession: "Kelner", district: "Śródmieście", distanceKm: 1, rate: 42, hours: 6, when: "now", employer: "Hotel Bristol", employerVerified: true, postedAgo: "30 min temu", description: "Obsługa kelnerska na konferencji. Praca od zaraz, kilka terminów." },
  { id: "j3", title: "Kucharz na zastępstwo", profession: "Kucharz", district: "Wola", distanceKm: 4, rate: 60, hours: 10, when: "now", employer: "Bistro Centralne", employerVerified: false, postedAgo: "1 godz. temu", description: "Kuchnia europejska, praca na linii. Stałe zlecenie z możliwością przedłużenia." },
  { id: "j4", title: "Pomoc kuchenna", profession: "Pomoc kuchenna", district: "Praga Południe", distanceKm: 6, rate: 33, hours: 8, when: "week", whenDate: "pn–pt", employer: "Catering Smaki", employerVerified: true, postedAgo: "3 godz. temu", description: "Przygotowanie składników, zmywak, porządki. Bez wymaganego doświadczenia." },
  { id: "j5", title: "Barista do kawiarni", profession: "Barista", district: "Ochota", distanceKm: 3, rate: 38, hours: 7, when: "week", whenDate: "weekendy", employer: "Kawiarnia Mela", employerVerified: true, postedAgo: "wczoraj", description: "Latte art mile widziane. Praca weekendowa, miła atmosfera." },
  { id: "j6", title: "Mixolog na otwarcie lokalu", profession: "Mixolog", district: "Śródmieście", distanceKm: 2, rate: 70, hours: 6, when: "date", whenDate: "20 cze", employer: "Tonic Bar", employerVerified: false, postedAgo: "2 dni temu", description: "Autorska karta koktajli na event otwarcia. Portfolio mile widziane." },
  { id: "j7", title: "Hostessa — targi", profession: "Hostessa", district: "Wola", distanceKm: 5, rate: 40, hours: 9, when: "date", whenDate: "25–27 cze", employer: "Expo Group", employerVerified: true, postedAgo: "wczoraj", description: "Obsługa stoiska na targach. Komunikatywny angielski wymagany." },
  { id: "j8", title: "Kierowca C+E — dostawy", profession: "Kierowca C+E", district: "Targówek", distanceKm: 7, rate: 55, hours: 10, when: "week", whenDate: "pn–sob", employer: "TransPol", employerVerified: true, postedAgo: "4 godz. temu", description: "Trasy lokalne na terenie Warszawy. Aktualne uprawnienia i karta kierowcy." },
  { id: "j9", title: "Elektryk SEP — montaż", profession: "Elektryk SEP", district: "Ursynów", distanceKm: 8, rate: 65, hours: 8, when: "now", employer: "InstalDom", employerVerified: false, postedAgo: "5 godz. temu", description: "Montaż instalacji w nowym budynku. Wymagane uprawnienia SEP do 1kV." },
  { id: "j10", title: "Sprzątanie biur — wieczory", profession: "Sprzątanie", district: "Mokotów", distanceKm: 3, rate: 35, hours: 4, when: "week", whenDate: "pn–pt wieczory", employer: "CleanOffice", employerVerified: true, postedAgo: "wczoraj", description: "Sprzątanie powierzchni biurowej po godzinach. Stałe, długoterminowe zlecenie." },
  { id: "j11", title: "Magazynier", profession: "Magazynier", district: "Włochy", distanceKm: 9, rate: 34, hours: 8, when: "now", employer: "LogiHub", employerVerified: true, postedAgo: "1 godz. temu", description: "Kompletacja zamówień, obsługa skanera. Praca zmianowa." },
  { id: "j12", title: "Kelner — restauracja sushi", profession: "Kelner", district: "Wilanów", distanceKm: 12, rate: 44, hours: 7, when: "week", whenDate: "czw–nd", employer: "Sushi Zen", employerVerified: true, postedAgo: "2 dni temu", description: "Obsługa sali, znajomość menu sushi mile widziana. Napiwki." },
];
